services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    ports:
      - "5010:5432"
    volumes:
      - /Users/nuno/Documents/dev/db_volumes/patient-service:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - patient-management-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      patient-service-db:
        condition: service_healthy
    networks:
      - patient-management-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    networks:
      - patient-management-network
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

networks:
  patient-management-network:
    external: true